package lexicalanalyser

// Code generated by peg -switch -inline -strict -output pkg/grammar.go pkg/grammar.peg DO NOT EDIT.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	rulefirst
	ruleFUNCTIONS
	ruleFUNCTION
	rulePARAMS_VARS
	ruleVAR_LIST
	ruleVAR_LIST1
	ruleTYPE
	ruleBODY
	ruleSTATEMENTS
	ruleSTATEMENT
	ruleELSECLAUSE
	ruleRETURN_CLAUSE
	ruleVALUE
	ruleEXPR_VALUE
	ruleBOOL_EXPR_VALUE
	ruleINDEXED
	ruleINDEXABLE
	ruleBOOL_EXPRESSION
	ruleBOOL_EXPRESSION1
	ruleBOOL_OP
	ruleASSIGNMENT
	ruleFUNC_CALL
	ruleEXPRESSION
	ruleEXPRESSION1
	ruleOP
	ruleASSIGNABLE
	ruleID
	ruleFIRST_CHAR
	ruleID1
	ruleINTEGER
	ruleBOOLEAN
	ruleSTRING
	ruleCHARS_IN_STRING
	ruleINT
	ruleARRAY
	ruleARRAY_CONTENT
	ruleARRAY_CONTENT1
	ruleMAP
	ruleKEY_VALUE_PAIRS
	ruleKEY_VALUE_PAIRS1
	ruleWHITESPACE_AT_LEAST_ONE
	ruleWHITESPACE_ANY
	ruleWHITESPACEC
	ruleAT_LEAST_ONE_SPACE
	ruleJUST_SPACES
)

var rul3s = [...]string{
	"Unknown",
	"first",
	"FUNCTIONS",
	"FUNCTION",
	"PARAMS_VARS",
	"VAR_LIST",
	"VAR_LIST1",
	"TYPE",
	"BODY",
	"STATEMENTS",
	"STATEMENT",
	"ELSECLAUSE",
	"RETURN_CLAUSE",
	"VALUE",
	"EXPR_VALUE",
	"BOOL_EXPR_VALUE",
	"INDEXED",
	"INDEXABLE",
	"BOOL_EXPRESSION",
	"BOOL_EXPRESSION1",
	"BOOL_OP",
	"ASSIGNMENT",
	"FUNC_CALL",
	"EXPRESSION",
	"EXPRESSION1",
	"OP",
	"ASSIGNABLE",
	"ID",
	"FIRST_CHAR",
	"ID1",
	"INTEGER",
	"BOOLEAN",
	"STRING",
	"CHARS_IN_STRING",
	"INT",
	"ARRAY",
	"ARRAY_CONTENT",
	"ARRAY_CONTENT1",
	"MAP",
	"KEY_VALUE_PAIRS",
	"KEY_VALUE_PAIRS1",
	"WHITESPACE_AT_LEAST_ONE",
	"WHITESPACE_ANY",
	"WHITESPACEC",
	"AT_LEAST_ONE_SPACE",
	"JUST_SPACES",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[34m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type MyParser struct {
	Buffer string
	buffer []rune
	rules  [46]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *MyParser) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *MyParser) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *MyParser
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *MyParser) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *MyParser) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func Pretty(pretty bool) func(*MyParser) error {
	return func(p *MyParser) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*MyParser) error {
	return func(p *MyParser) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *MyParser) Init(options ...func(*MyParser) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 first <- <('g' 'l' 'o' 'b' 'a' 'l' 's' WHITESPACE_AT_LEAST_ONE PARAMS_VARS* ('e' 'n' 'd' 'g' 'l' 'o' 'b' 'a' 'l' 's') WHITESPACE_AT_LEAST_ONE FUNCTIONS ('m' 'a' 'i' 'n') WHITESPACE_ANY BODY ('e' 'n' 'd' 'm' 'a' 'i' 'n') WHITESPACE_ANY !.)> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				if buffer[position] != rune('g') {
					goto l0
				}
				position++
				if buffer[position] != rune('l') {
					goto l0
				}
				position++
				if buffer[position] != rune('o') {
					goto l0
				}
				position++
				if buffer[position] != rune('b') {
					goto l0
				}
				position++
				if buffer[position] != rune('a') {
					goto l0
				}
				position++
				if buffer[position] != rune('l') {
					goto l0
				}
				position++
				if buffer[position] != rune('s') {
					goto l0
				}
				position++
				if !_rules[ruleWHITESPACE_AT_LEAST_ONE]() {
					goto l0
				}
			l2:
				{
					position3, tokenIndex3 := position, tokenIndex
					if !_rules[rulePARAMS_VARS]() {
						goto l3
					}
					goto l2
				l3:
					position, tokenIndex = position3, tokenIndex3
				}
				if buffer[position] != rune('e') {
					goto l0
				}
				position++
				if buffer[position] != rune('n') {
					goto l0
				}
				position++
				if buffer[position] != rune('d') {
					goto l0
				}
				position++
				if buffer[position] != rune('g') {
					goto l0
				}
				position++
				if buffer[position] != rune('l') {
					goto l0
				}
				position++
				if buffer[position] != rune('o') {
					goto l0
				}
				position++
				if buffer[position] != rune('b') {
					goto l0
				}
				position++
				if buffer[position] != rune('a') {
					goto l0
				}
				position++
				if buffer[position] != rune('l') {
					goto l0
				}
				position++
				if buffer[position] != rune('s') {
					goto l0
				}
				position++
				if !_rules[ruleWHITESPACE_AT_LEAST_ONE]() {
					goto l0
				}
				{
					position4 := position
				l5:
					{
						position6, tokenIndex6 := position, tokenIndex
						{
							position7 := position
							if buffer[position] != rune('f') {
								goto l6
							}
							position++
							if buffer[position] != rune('u') {
								goto l6
							}
							position++
							if buffer[position] != rune('n') {
								goto l6
							}
							position++
							if buffer[position] != rune('c') {
								goto l6
							}
							position++
							if !_rules[ruleAT_LEAST_ONE_SPACE]() {
								goto l6
							}
							if !_rules[ruleID]() {
								goto l6
							}
							if !_rules[ruleJUST_SPACES]() {
								goto l6
							}
							if buffer[position] != rune('(') {
								goto l6
							}
							position++
							if !_rules[ruleWHITESPACE_ANY]() {
								goto l6
							}
						l8:
							{
								position9, tokenIndex9 := position, tokenIndex
								if !_rules[rulePARAMS_VARS]() {
									goto l9
								}
								goto l8
							l9:
								position, tokenIndex = position9, tokenIndex9
							}
							if buffer[position] != rune(')') {
								goto l6
							}
							position++
							if !_rules[ruleJUST_SPACES]() {
								goto l6
							}
							if buffer[position] != rune(':') {
								goto l6
							}
							position++
							if !_rules[ruleJUST_SPACES]() {
								goto l6
							}
							if !_rules[ruleTYPE]() {
								goto l6
							}
							if !_rules[ruleWHITESPACE_ANY]() {
								goto l6
							}
							if !_rules[ruleBODY]() {
								goto l6
							}
							add(ruleFUNCTION, position7)
						}
						goto l5
					l6:
						position, tokenIndex = position6, tokenIndex6
					}
					add(ruleFUNCTIONS, position4)
				}
				if buffer[position] != rune('m') {
					goto l0
				}
				position++
				if buffer[position] != rune('a') {
					goto l0
				}
				position++
				if buffer[position] != rune('i') {
					goto l0
				}
				position++
				if buffer[position] != rune('n') {
					goto l0
				}
				position++
				if !_rules[ruleWHITESPACE_ANY]() {
					goto l0
				}
				if !_rules[ruleBODY]() {
					goto l0
				}
				if buffer[position] != rune('e') {
					goto l0
				}
				position++
				if buffer[position] != rune('n') {
					goto l0
				}
				position++
				if buffer[position] != rune('d') {
					goto l0
				}
				position++
				if buffer[position] != rune('m') {
					goto l0
				}
				position++
				if buffer[position] != rune('a') {
					goto l0
				}
				position++
				if buffer[position] != rune('i') {
					goto l0
				}
				position++
				if buffer[position] != rune('n') {
					goto l0
				}
				position++
				if !_rules[ruleWHITESPACE_ANY]() {
					goto l0
				}
				{
					position10, tokenIndex10 := position, tokenIndex
					if !matchDot() {
						goto l10
					}
					goto l0
				l10:
					position, tokenIndex = position10, tokenIndex10
				}
				add(rulefirst, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 FUNCTIONS <- <FUNCTION*> */
		nil,
		/* 2 FUNCTION <- <('f' 'u' 'n' 'c' AT_LEAST_ONE_SPACE ID JUST_SPACES '(' WHITESPACE_ANY PARAMS_VARS* ')' JUST_SPACES ':' JUST_SPACES TYPE WHITESPACE_ANY BODY)> */
		nil,
		/* 3 PARAMS_VARS <- <(TYPE JUST_SPACES '[' JUST_SPACES VAR_LIST ']' WHITESPACE_ANY PARAMS_VARS* WHITESPACE_ANY)> */
		func() bool {
			position13, tokenIndex13 := position, tokenIndex
			{
				position14 := position
				if !_rules[ruleTYPE]() {
					goto l13
				}
				if !_rules[ruleJUST_SPACES]() {
					goto l13
				}
				if buffer[position] != rune('[') {
					goto l13
				}
				position++
				if !_rules[ruleJUST_SPACES]() {
					goto l13
				}
				if !_rules[ruleVAR_LIST]() {
					goto l13
				}
				if buffer[position] != rune(']') {
					goto l13
				}
				position++
				if !_rules[ruleWHITESPACE_ANY]() {
					goto l13
				}
			l15:
				{
					position16, tokenIndex16 := position, tokenIndex
					if !_rules[rulePARAMS_VARS]() {
						goto l16
					}
					goto l15
				l16:
					position, tokenIndex = position16, tokenIndex16
				}
				if !_rules[ruleWHITESPACE_ANY]() {
					goto l13
				}
				add(rulePARAMS_VARS, position14)
			}
			return true
		l13:
			position, tokenIndex = position13, tokenIndex13
			return false
		},
		/* 4 VAR_LIST <- <(ID VAR_LIST1* WHITESPACE_ANY)> */
		func() bool {
			position17, tokenIndex17 := position, tokenIndex
			{
				position18 := position
				if !_rules[ruleID]() {
					goto l17
				}
			l19:
				{
					position20, tokenIndex20 := position, tokenIndex
					if !_rules[ruleVAR_LIST1]() {
						goto l20
					}
					goto l19
				l20:
					position, tokenIndex = position20, tokenIndex20
				}
				if !_rules[ruleWHITESPACE_ANY]() {
					goto l17
				}
				add(ruleVAR_LIST, position18)
			}
			return true
		l17:
			position, tokenIndex = position17, tokenIndex17
			return false
		},
		/* 5 VAR_LIST1 <- <(JUST_SPACES ',' JUST_SPACES VAR_LIST VAR_LIST1* JUST_SPACES)> */
		func() bool {
			position21, tokenIndex21 := position, tokenIndex
			{
				position22 := position
				if !_rules[ruleJUST_SPACES]() {
					goto l21
				}
				if buffer[position] != rune(',') {
					goto l21
				}
				position++
				if !_rules[ruleJUST_SPACES]() {
					goto l21
				}
				if !_rules[ruleVAR_LIST]() {
					goto l21
				}
			l23:
				{
					position24, tokenIndex24 := position, tokenIndex
					if !_rules[ruleVAR_LIST1]() {
						goto l24
					}
					goto l23
				l24:
					position, tokenIndex = position24, tokenIndex24
				}
				if !_rules[ruleJUST_SPACES]() {
					goto l21
				}
				add(ruleVAR_LIST1, position22)
			}
			return true
		l21:
			position, tokenIndex = position21, tokenIndex21
			return false
		},
		/* 6 TYPE <- <((&('v') ('v' 'o' 'i' 'd')) | (&('b') ('b' 'o' 'o' 'l')) | (&('m') ('m' 'a' 'p' '[' TYPE ']' TYPE)) | (&('[') ('[' [0-9]+ ']' TYPE)) | (&('i') ('i' 'n' 't')) | (&('s') ('s' 't' 'r' 'i' 'n' 'g')))> */
		func() bool {
			position25, tokenIndex25 := position, tokenIndex
			{
				position26 := position
				{
					switch buffer[position] {
					case 'v':
						if buffer[position] != rune('v') {
							goto l25
						}
						position++
						if buffer[position] != rune('o') {
							goto l25
						}
						position++
						if buffer[position] != rune('i') {
							goto l25
						}
						position++
						if buffer[position] != rune('d') {
							goto l25
						}
						position++
					case 'b':
						if buffer[position] != rune('b') {
							goto l25
						}
						position++
						if buffer[position] != rune('o') {
							goto l25
						}
						position++
						if buffer[position] != rune('o') {
							goto l25
						}
						position++
						if buffer[position] != rune('l') {
							goto l25
						}
						position++
					case 'm':
						if buffer[position] != rune('m') {
							goto l25
						}
						position++
						if buffer[position] != rune('a') {
							goto l25
						}
						position++
						if buffer[position] != rune('p') {
							goto l25
						}
						position++
						if buffer[position] != rune('[') {
							goto l25
						}
						position++
						if !_rules[ruleTYPE]() {
							goto l25
						}
						if buffer[position] != rune(']') {
							goto l25
						}
						position++
						if !_rules[ruleTYPE]() {
							goto l25
						}
					case '[':
						if buffer[position] != rune('[') {
							goto l25
						}
						position++
						if c := buffer[position]; c < rune('0') || c > rune('9') {
							goto l25
						}
						position++
					l28:
						{
							position29, tokenIndex29 := position, tokenIndex
							if c := buffer[position]; c < rune('0') || c > rune('9') {
								goto l29
							}
							position++
							goto l28
						l29:
							position, tokenIndex = position29, tokenIndex29
						}
						if buffer[position] != rune(']') {
							goto l25
						}
						position++
						if !_rules[ruleTYPE]() {
							goto l25
						}
					case 'i':
						if buffer[position] != rune('i') {
							goto l25
						}
						position++
						if buffer[position] != rune('n') {
							goto l25
						}
						position++
						if buffer[position] != rune('t') {
							goto l25
						}
						position++
					default:
						if buffer[position] != rune('s') {
							goto l25
						}
						position++
						if buffer[position] != rune('t') {
							goto l25
						}
						position++
						if buffer[position] != rune('r') {
							goto l25
						}
						position++
						if buffer[position] != rune('i') {
							goto l25
						}
						position++
						if buffer[position] != rune('n') {
							goto l25
						}
						position++
						if buffer[position] != rune('g') {
							goto l25
						}
						position++
					}
				}

				add(ruleTYPE, position26)
			}
			return true
		l25:
			position, tokenIndex = position25, tokenIndex25
			return false
		},
		/* 7 BODY <- <('{' WHITESPACE_ANY PARAMS_VARS* ';' WHITESPACE_ANY STATEMENTS* RETURN_CLAUSE? WHITESPACE_ANY '}' WHITESPACE_ANY)> */
		func() bool {
			position30, tokenIndex30 := position, tokenIndex
			{
				position31 := position
				if buffer[position] != rune('{') {
					goto l30
				}
				position++
				if !_rules[ruleWHITESPACE_ANY]() {
					goto l30
				}
			l32:
				{
					position33, tokenIndex33 := position, tokenIndex
					if !_rules[rulePARAMS_VARS]() {
						goto l33
					}
					goto l32
				l33:
					position, tokenIndex = position33, tokenIndex33
				}
				if buffer[position] != rune(';') {
					goto l30
				}
				position++
				if !_rules[ruleWHITESPACE_ANY]() {
					goto l30
				}
			l34:
				{
					position35, tokenIndex35 := position, tokenIndex
					if !_rules[ruleSTATEMENTS]() {
						goto l35
					}
					goto l34
				l35:
					position, tokenIndex = position35, tokenIndex35
				}
				{
					position36, tokenIndex36 := position, tokenIndex
					{
						position38 := position
						if !_rules[ruleWHITESPACE_ANY]() {
							goto l36
						}
						if buffer[position] != rune('r') {
							goto l36
						}
						position++
						if buffer[position] != rune('e') {
							goto l36
						}
						position++
						if buffer[position] != rune('t') {
							goto l36
						}
						position++
						if buffer[position] != rune('u') {
							goto l36
						}
						position++
						if buffer[position] != rune('r') {
							goto l36
						}
						position++
						if buffer[position] != rune('n') {
							goto l36
						}
						position++
						if !_rules[ruleAT_LEAST_ONE_SPACE]() {
							goto l36
						}
						if !_rules[ruleVALUE]() {
							goto l36
						}
						add(ruleRETURN_CLAUSE, position38)
					}
					goto l37
				l36:
					position, tokenIndex = position36, tokenIndex36
				}
			l37:
				if !_rules[ruleWHITESPACE_ANY]() {
					goto l30
				}
				if buffer[position] != rune('}') {
					goto l30
				}
				position++
				if !_rules[ruleWHITESPACE_ANY]() {
					goto l30
				}
				add(ruleBODY, position31)
			}
			return true
		l30:
			position, tokenIndex = position30, tokenIndex30
			return false
		},
		/* 8 STATEMENTS <- <(STATEMENT STATEMENTS*)> */
		func() bool {
			position39, tokenIndex39 := position, tokenIndex
			{
				position40 := position
				{
					position41 := position
					{
						position42, tokenIndex42 := position, tokenIndex
						{
							position44 := position
							{
								position45, tokenIndex45 := position, tokenIndex
								if buffer[position] != rune('v') {
									goto l46
								}
								position++
								if buffer[position] != rune('a') {
									goto l46
								}
								position++
								if buffer[position] != rune('r') {
									goto l46
								}
								position++
								if !_rules[ruleAT_LEAST_ONE_SPACE]() {
									goto l46
								}
								if !_rules[ruleASSIGNABLE]() {
									goto l46
								}
								if !_rules[ruleAT_LEAST_ONE_SPACE]() {
									goto l46
								}
								if !_rules[ruleTYPE]() {
									goto l46
								}
								if !_rules[ruleJUST_SPACES]() {
									goto l46
								}
								if buffer[position] != rune('=') {
									goto l46
								}
								position++
								if !_rules[ruleJUST_SPACES]() {
									goto l46
								}
								if !_rules[ruleVALUE]() {
									goto l46
								}
								goto l45
							l46:
								position, tokenIndex = position45, tokenIndex45
								if buffer[position] != rune('l') {
									goto l47
								}
								position++
								if buffer[position] != rune('e') {
									goto l47
								}
								position++
								if buffer[position] != rune('t') {
									goto l47
								}
								position++
								if !_rules[ruleAT_LEAST_ONE_SPACE]() {
									goto l47
								}
								if !_rules[ruleASSIGNABLE]() {
									goto l47
								}
								if !_rules[ruleJUST_SPACES]() {
									goto l47
								}
								if buffer[position] != rune('=') {
									goto l47
								}
								position++
								if !_rules[ruleJUST_SPACES]() {
									goto l47
								}
								if !_rules[ruleVALUE]() {
									goto l47
								}
								goto l45
							l47:
								position, tokenIndex = position45, tokenIndex45
								if !_rules[ruleASSIGNABLE]() {
									goto l43
								}
								if !_rules[ruleJUST_SPACES]() {
									goto l43
								}
								if buffer[position] != rune('=') {
									goto l43
								}
								position++
								if !_rules[ruleJUST_SPACES]() {
									goto l43
								}
								if !_rules[ruleVALUE]() {
									goto l43
								}
							}
						l45:
							add(ruleASSIGNMENT, position44)
						}
						if !_rules[ruleWHITESPACE_ANY]() {
							goto l43
						}
						goto l42
					l43:
						position, tokenIndex = position42, tokenIndex42
						{
							switch buffer[position] {
							case 'p':
								if buffer[position] != rune('p') {
									goto l39
								}
								position++
								if buffer[position] != rune('r') {
									goto l39
								}
								position++
								if buffer[position] != rune('i') {
									goto l39
								}
								position++
								if buffer[position] != rune('n') {
									goto l39
								}
								position++
								if buffer[position] != rune('t') {
									goto l39
								}
								position++
								if buffer[position] != rune('(') {
									goto l39
								}
								position++
								if !_rules[ruleWHITESPACE_ANY]() {
									goto l39
								}
								if !_rules[ruleVALUE]() {
									goto l39
								}
								if !_rules[ruleWHITESPACE_ANY]() {
									goto l39
								}
								if buffer[position] != rune(')') {
									goto l39
								}
								position++
							case 'c':
								if !_rules[ruleFUNC_CALL]() {
									goto l39
								}
								if !_rules[ruleWHITESPACE_ANY]() {
									goto l39
								}
							case 'w':
								if buffer[position] != rune('w') {
									goto l39
								}
								position++
								if buffer[position] != rune('h') {
									goto l39
								}
								position++
								if buffer[position] != rune('i') {
									goto l39
								}
								position++
								if buffer[position] != rune('l') {
									goto l39
								}
								position++
								if buffer[position] != rune('e') {
									goto l39
								}
								position++
								if !_rules[ruleAT_LEAST_ONE_SPACE]() {
									goto l39
								}
								if !_rules[ruleBOOL_EXPRESSION]() {
									goto l39
								}
								if !_rules[ruleAT_LEAST_ONE_SPACE]() {
									goto l39
								}
								if !_rules[ruleBODY]() {
									goto l39
								}
								if !_rules[ruleWHITESPACE_ANY]() {
									goto l39
								}
							default:
								if buffer[position] != rune('i') {
									goto l39
								}
								position++
								if buffer[position] != rune('f') {
									goto l39
								}
								position++
								if !_rules[ruleAT_LEAST_ONE_SPACE]() {
									goto l39
								}
								if !_rules[ruleBOOL_EXPRESSION]() {
									goto l39
								}
								if !_rules[ruleAT_LEAST_ONE_SPACE]() {
									goto l39
								}
								if !_rules[ruleBODY]() {
									goto l39
								}
								{
									position49, tokenIndex49 := position, tokenIndex
									{
										position51 := position
										if !_rules[ruleWHITESPACE_ANY]() {
											goto l49
										}
										if buffer[position] != rune('e') {
											goto l49
										}
										position++
										if buffer[position] != rune('l') {
											goto l49
										}
										position++
										if buffer[position] != rune('s') {
											goto l49
										}
										position++
										if buffer[position] != rune('e') {
											goto l49
										}
										position++
										if !_rules[ruleWHITESPACE_ANY]() {
											goto l49
										}
										if !_rules[ruleBODY]() {
											goto l49
										}
										add(ruleELSECLAUSE, position51)
									}
									goto l50
								l49:
									position, tokenIndex = position49, tokenIndex49
								}
							l50:
								if !_rules[ruleWHITESPACE_ANY]() {
									goto l39
								}
							}
						}

					}
				l42:
					add(ruleSTATEMENT, position41)
				}
			l52:
				{
					position53, tokenIndex53 := position, tokenIndex
					if !_rules[ruleSTATEMENTS]() {
						goto l53
					}
					goto l52
				l53:
					position, tokenIndex = position53, tokenIndex53
				}
				add(ruleSTATEMENTS, position40)
			}
			return true
		l39:
			position, tokenIndex = position39, tokenIndex39
			return false
		},
		/* 9 STATEMENT <- <((ASSIGNMENT WHITESPACE_ANY) / ((&('p') ('p' 'r' 'i' 'n' 't' '(' WHITESPACE_ANY VALUE WHITESPACE_ANY ')')) | (&('c') (FUNC_CALL WHITESPACE_ANY)) | (&('w') ('w' 'h' 'i' 'l' 'e' AT_LEAST_ONE_SPACE BOOL_EXPRESSION AT_LEAST_ONE_SPACE BODY WHITESPACE_ANY)) | (&('i') ('i' 'f' AT_LEAST_ONE_SPACE BOOL_EXPRESSION AT_LEAST_ONE_SPACE BODY ELSECLAUSE? WHITESPACE_ANY))))> */
		nil,
		/* 10 ELSECLAUSE <- <(WHITESPACE_ANY ('e' 'l' 's' 'e') WHITESPACE_ANY BODY)> */
		nil,
		/* 11 RETURN_CLAUSE <- <(WHITESPACE_ANY ('r' 'e' 't' 'u' 'r' 'n') AT_LEAST_ONE_SPACE VALUE)> */
		nil,
		/* 12 VALUE <- <(('v' 'a' 'r' AT_LEAST_ONE_SPACE ID) / ('a' 'r' 'r' AT_LEAST_ONE_SPACE ID INDEXED?) / FUNC_CALL / ('v' 'o' 'i' 'd') / STRING / INTEGER / BOOLEAN / ARRAY / EXPRESSION / BOOL_EXPRESSION / MAP)> */
		func() bool {
			position57, tokenIndex57 := position, tokenIndex
			{
				position58 := position
				{
					position59, tokenIndex59 := position, tokenIndex
					if buffer[position] != rune('v') {
						goto l60
					}
					position++
					if buffer[position] != rune('a') {
						goto l60
					}
					position++
					if buffer[position] != rune('r') {
						goto l60
					}
					position++
					if !_rules[ruleAT_LEAST_ONE_SPACE]() {
						goto l60
					}
					if !_rules[ruleID]() {
						goto l60
					}
					goto l59
				l60:
					position, tokenIndex = position59, tokenIndex59
					if buffer[position] != rune('a') {
						goto l61
					}
					position++
					if buffer[position] != rune('r') {
						goto l61
					}
					position++
					if buffer[position] != rune('r') {
						goto l61
					}
					position++
					if !_rules[ruleAT_LEAST_ONE_SPACE]() {
						goto l61
					}
					if !_rules[ruleID]() {
						goto l61
					}
					{
						position62, tokenIndex62 := position, tokenIndex
						if !_rules[ruleINDEXED]() {
							goto l62
						}
						goto l63
					l62:
						position, tokenIndex = position62, tokenIndex62
					}
				l63:
					goto l59
				l61:
					position, tokenIndex = position59, tokenIndex59
					if !_rules[ruleFUNC_CALL]() {
						goto l64
					}
					goto l59
				l64:
					position, tokenIndex = position59, tokenIndex59
					if buffer[position] != rune('v') {
						goto l65
					}
					position++
					if buffer[position] != rune('o') {
						goto l65
					}
					position++
					if buffer[position] != rune('i') {
						goto l65
					}
					position++
					if buffer[position] != rune('d') {
						goto l65
					}
					position++
					goto l59
				l65:
					position, tokenIndex = position59, tokenIndex59
					if !_rules[ruleSTRING]() {
						goto l66
					}
					goto l59
				l66:
					position, tokenIndex = position59, tokenIndex59
					if !_rules[ruleINTEGER]() {
						goto l67
					}
					goto l59
				l67:
					position, tokenIndex = position59, tokenIndex59
					if !_rules[ruleBOOLEAN]() {
						goto l68
					}
					goto l59
				l68:
					position, tokenIndex = position59, tokenIndex59
					if !_rules[ruleARRAY]() {
						goto l69
					}
					goto l59
				l69:
					position, tokenIndex = position59, tokenIndex59
					if !_rules[ruleEXPRESSION]() {
						goto l70
					}
					goto l59
				l70:
					position, tokenIndex = position59, tokenIndex59
					if !_rules[ruleBOOL_EXPRESSION]() {
						goto l71
					}
					goto l59
				l71:
					position, tokenIndex = position59, tokenIndex59
					{
						position72 := position
						if buffer[position] != rune('(') {
							goto l57
						}
						position++
						if !_rules[ruleKEY_VALUE_PAIRS]() {
							goto l57
						}
						if buffer[position] != rune(')') {
							goto l57
						}
						position++
						add(ruleMAP, position72)
					}
				}
			l59:
				add(ruleVALUE, position58)
			}
			return true
		l57:
			position, tokenIndex = position57, tokenIndex57
			return false
		},
		/* 13 EXPR_VALUE <- <(('a' 'r' 'r' AT_LEAST_ONE_SPACE ID INDEXED) / FUNC_CALL / ((&('[') ARRAY) | (&('"') STRING) | (&('-' | '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9') INTEGER) | (&('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z' | '_' | 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z') ID)))> */
		nil,
		/* 14 BOOL_EXPR_VALUE <- <(BOOLEAN / ('a' 'r' 'r' AT_LEAST_ONE_SPACE ID INDEXED) / ((&('"') STRING) | (&('-' | '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9') INTEGER) | (&('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z' | '_' | 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z') ID)))> */
		nil,
		/* 15 INDEXED <- <('[' INDEXABLE ']')> */
		func() bool {
			position75, tokenIndex75 := position, tokenIndex
			{
				position76 := position
				if buffer[position] != rune('[') {
					goto l75
				}
				position++
				if !_rules[ruleINDEXABLE]() {
					goto l75
				}
				if buffer[position] != rune(']') {
					goto l75
				}
				position++
				add(ruleINDEXED, position76)
			}
			return true
		l75:
			position, tokenIndex = position75, tokenIndex75
			return false
		},
		/* 16 INDEXABLE <- <(('v' 'a' 'r' AT_LEAST_ONE_SPACE ID) / INT)> */
		func() bool {
			position77, tokenIndex77 := position, tokenIndex
			{
				position78 := position
				{
					position79, tokenIndex79 := position, tokenIndex
					if buffer[position] != rune('v') {
						goto l80
					}
					position++
					if buffer[position] != rune('a') {
						goto l80
					}
					position++
					if buffer[position] != rune('r') {
						goto l80
					}
					position++
					if !_rules[ruleAT_LEAST_ONE_SPACE]() {
						goto l80
					}
					if !_rules[ruleID]() {
						goto l80
					}
					goto l79
				l80:
					position, tokenIndex = position79, tokenIndex79
					if !_rules[ruleINT]() {
						goto l77
					}
				}
			l79:
				add(ruleINDEXABLE, position78)
			}
			return true
		l77:
			position, tokenIndex = position77, tokenIndex77
			return false
		},
		/* 17 BOOL_EXPRESSION <- <(BOOL_EXPR_VALUE BOOL_EXPRESSION1*)> */
		func() bool {
			position81, tokenIndex81 := position, tokenIndex
			{
				position82 := position
				{
					position83 := position
					{
						position84, tokenIndex84 := position, tokenIndex
						if !_rules[ruleBOOLEAN]() {
							goto l85
						}
						goto l84
					l85:
						position, tokenIndex = position84, tokenIndex84
						if buffer[position] != rune('a') {
							goto l86
						}
						position++
						if buffer[position] != rune('r') {
							goto l86
						}
						position++
						if buffer[position] != rune('r') {
							goto l86
						}
						position++
						if !_rules[ruleAT_LEAST_ONE_SPACE]() {
							goto l86
						}
						if !_rules[ruleID]() {
							goto l86
						}
						if !_rules[ruleINDEXED]() {
							goto l86
						}
						goto l84
					l86:
						position, tokenIndex = position84, tokenIndex84
						{
							switch buffer[position] {
							case '"':
								if !_rules[ruleSTRING]() {
									goto l81
								}
							case '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
								if !_rules[ruleINTEGER]() {
									goto l81
								}
							default:
								if !_rules[ruleID]() {
									goto l81
								}
							}
						}

					}
				l84:
					add(ruleBOOL_EXPR_VALUE, position83)
				}
			l88:
				{
					position89, tokenIndex89 := position, tokenIndex
					if !_rules[ruleBOOL_EXPRESSION1]() {
						goto l89
					}
					goto l88
				l89:
					position, tokenIndex = position89, tokenIndex89
				}
				add(ruleBOOL_EXPRESSION, position82)
			}
			return true
		l81:
			position, tokenIndex = position81, tokenIndex81
			return false
		},
		/* 18 BOOL_EXPRESSION1 <- <(JUST_SPACES BOOL_OP JUST_SPACES BOOL_EXPRESSION BOOL_EXPRESSION1*)> */
		func() bool {
			position90, tokenIndex90 := position, tokenIndex
			{
				position91 := position
				if !_rules[ruleJUST_SPACES]() {
					goto l90
				}
				{
					position92 := position
					{
						position93, tokenIndex93 := position, tokenIndex
						if buffer[position] != rune('<') {
							goto l94
						}
						position++
						if buffer[position] != rune('=') {
							goto l94
						}
						position++
						goto l93
					l94:
						position, tokenIndex = position93, tokenIndex93
						if buffer[position] != rune('>') {
							goto l95
						}
						position++
						if buffer[position] != rune('=') {
							goto l95
						}
						position++
						goto l93
					l95:
						position, tokenIndex = position93, tokenIndex93
						{
							switch buffer[position] {
							case '!':
								if buffer[position] != rune('!') {
									goto l90
								}
								position++
								if buffer[position] != rune('=') {
									goto l90
								}
								position++
							case '=':
								if buffer[position] != rune('=') {
									goto l90
								}
								position++
								if buffer[position] != rune('=') {
									goto l90
								}
								position++
							case '>':
								if buffer[position] != rune('>') {
									goto l90
								}
								position++
							default:
								if buffer[position] != rune('<') {
									goto l90
								}
								position++
							}
						}

					}
				l93:
					add(ruleBOOL_OP, position92)
				}
				if !_rules[ruleJUST_SPACES]() {
					goto l90
				}
				if !_rules[ruleBOOL_EXPRESSION]() {
					goto l90
				}
			l97:
				{
					position98, tokenIndex98 := position, tokenIndex
					if !_rules[ruleBOOL_EXPRESSION1]() {
						goto l98
					}
					goto l97
				l98:
					position, tokenIndex = position98, tokenIndex98
				}
				add(ruleBOOL_EXPRESSION1, position91)
			}
			return true
		l90:
			position, tokenIndex = position90, tokenIndex90
			return false
		},
		/* 19 BOOL_OP <- <(('<' '=') / ('>' '=') / ((&('!') ('!' '=')) | (&('=') ('=' '=')) | (&('>') '>') | (&('<') '<')))> */
		nil,
		/* 20 ASSIGNMENT <- <(('v' 'a' 'r' AT_LEAST_ONE_SPACE ASSIGNABLE AT_LEAST_ONE_SPACE TYPE JUST_SPACES '=' JUST_SPACES VALUE) / ('l' 'e' 't' AT_LEAST_ONE_SPACE ASSIGNABLE JUST_SPACES '=' JUST_SPACES VALUE) / (ASSIGNABLE JUST_SPACES '=' JUST_SPACES VALUE))> */
		nil,
		/* 21 FUNC_CALL <- <('c' 'a' 'l' 'l' JUST_SPACES ID JUST_SPACES '(' WHITESPACE_ANY VAR_LIST* WHITESPACE_ANY ')')> */
		func() bool {
			position101, tokenIndex101 := position, tokenIndex
			{
				position102 := position
				if buffer[position] != rune('c') {
					goto l101
				}
				position++
				if buffer[position] != rune('a') {
					goto l101
				}
				position++
				if buffer[position] != rune('l') {
					goto l101
				}
				position++
				if buffer[position] != rune('l') {
					goto l101
				}
				position++
				if !_rules[ruleJUST_SPACES]() {
					goto l101
				}
				if !_rules[ruleID]() {
					goto l101
				}
				if !_rules[ruleJUST_SPACES]() {
					goto l101
				}
				if buffer[position] != rune('(') {
					goto l101
				}
				position++
				if !_rules[ruleWHITESPACE_ANY]() {
					goto l101
				}
			l103:
				{
					position104, tokenIndex104 := position, tokenIndex
					if !_rules[ruleVAR_LIST]() {
						goto l104
					}
					goto l103
				l104:
					position, tokenIndex = position104, tokenIndex104
				}
				if !_rules[ruleWHITESPACE_ANY]() {
					goto l101
				}
				if buffer[position] != rune(')') {
					goto l101
				}
				position++
				add(ruleFUNC_CALL, position102)
			}
			return true
		l101:
			position, tokenIndex = position101, tokenIndex101
			return false
		},
		/* 22 EXPRESSION <- <(EXPR_VALUE EXPRESSION1*)> */
		func() bool {
			position105, tokenIndex105 := position, tokenIndex
			{
				position106 := position
				{
					position107 := position
					{
						position108, tokenIndex108 := position, tokenIndex
						if buffer[position] != rune('a') {
							goto l109
						}
						position++
						if buffer[position] != rune('r') {
							goto l109
						}
						position++
						if buffer[position] != rune('r') {
							goto l109
						}
						position++
						if !_rules[ruleAT_LEAST_ONE_SPACE]() {
							goto l109
						}
						if !_rules[ruleID]() {
							goto l109
						}
						if !_rules[ruleINDEXED]() {
							goto l109
						}
						goto l108
					l109:
						position, tokenIndex = position108, tokenIndex108
						if !_rules[ruleFUNC_CALL]() {
							goto l110
						}
						goto l108
					l110:
						position, tokenIndex = position108, tokenIndex108
						{
							switch buffer[position] {
							case '[':
								if !_rules[ruleARRAY]() {
									goto l105
								}
							case '"':
								if !_rules[ruleSTRING]() {
									goto l105
								}
							case '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
								if !_rules[ruleINTEGER]() {
									goto l105
								}
							default:
								if !_rules[ruleID]() {
									goto l105
								}
							}
						}

					}
				l108:
					add(ruleEXPR_VALUE, position107)
				}
			l112:
				{
					position113, tokenIndex113 := position, tokenIndex
					if !_rules[ruleEXPRESSION1]() {
						goto l113
					}
					goto l112
				l113:
					position, tokenIndex = position113, tokenIndex113
				}
				add(ruleEXPRESSION, position106)
			}
			return true
		l105:
			position, tokenIndex = position105, tokenIndex105
			return false
		},
		/* 23 EXPRESSION1 <- <(JUST_SPACES OP JUST_SPACES EXPRESSION EXPRESSION1*)> */
		func() bool {
			position114, tokenIndex114 := position, tokenIndex
			{
				position115 := position
				if !_rules[ruleJUST_SPACES]() {
					goto l114
				}
				{
					position116 := position
					{
						switch buffer[position] {
						case '/':
							if buffer[position] != rune('/') {
								goto l114
							}
							position++
						case '*':
							if buffer[position] != rune('*') {
								goto l114
							}
							position++
						case '-':
							if buffer[position] != rune('-') {
								goto l114
							}
							position++
						default:
							if buffer[position] != rune('+') {
								goto l114
							}
							position++
						}
					}

					add(ruleOP, position116)
				}
				if !_rules[ruleJUST_SPACES]() {
					goto l114
				}
				if !_rules[ruleEXPRESSION]() {
					goto l114
				}
			l118:
				{
					position119, tokenIndex119 := position, tokenIndex
					if !_rules[ruleEXPRESSION1]() {
						goto l119
					}
					goto l118
				l119:
					position, tokenIndex = position119, tokenIndex119
				}
				add(ruleEXPRESSION1, position115)
			}
			return true
		l114:
			position, tokenIndex = position114, tokenIndex114
			return false
		},
		/* 24 OP <- <((&('/') '/') | (&('*') '*') | (&('-') '-') | (&('+') '+'))> */
		nil,
		/* 25 ASSIGNABLE <- <(('a' 'r' 'r' AT_LEAST_ONE_SPACE ID '[' INDEXABLE ']') / ID)> */
		func() bool {
			position121, tokenIndex121 := position, tokenIndex
			{
				position122 := position
				{
					position123, tokenIndex123 := position, tokenIndex
					if buffer[position] != rune('a') {
						goto l124
					}
					position++
					if buffer[position] != rune('r') {
						goto l124
					}
					position++
					if buffer[position] != rune('r') {
						goto l124
					}
					position++
					if !_rules[ruleAT_LEAST_ONE_SPACE]() {
						goto l124
					}
					if !_rules[ruleID]() {
						goto l124
					}
					if buffer[position] != rune('[') {
						goto l124
					}
					position++
					if !_rules[ruleINDEXABLE]() {
						goto l124
					}
					if buffer[position] != rune(']') {
						goto l124
					}
					position++
					goto l123
				l124:
					position, tokenIndex = position123, tokenIndex123
					if !_rules[ruleID]() {
						goto l121
					}
				}
			l123:
				add(ruleASSIGNABLE, position122)
			}
			return true
		l121:
			position, tokenIndex = position121, tokenIndex121
			return false
		},
		/* 26 ID <- <(FIRST_CHAR ID1*)> */
		func() bool {
			position125, tokenIndex125 := position, tokenIndex
			{
				position126 := position
				{
					position127 := position
					{
						switch buffer[position] {
						case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
							if c := buffer[position]; c < rune('A') || c > rune('Z') {
								goto l125
							}
							position++
						case '_':
							if buffer[position] != rune('_') {
								goto l125
							}
							position++
						default:
							if c := buffer[position]; c < rune('a') || c > rune('z') {
								goto l125
							}
							position++
						}
					}

					add(ruleFIRST_CHAR, position127)
				}
			l129:
				{
					position130, tokenIndex130 := position, tokenIndex
					{
						position131 := position
						{
							switch buffer[position] {
							case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
								if c := buffer[position]; c < rune('0') || c > rune('9') {
									goto l130
								}
								position++
							case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
								if c := buffer[position]; c < rune('A') || c > rune('Z') {
									goto l130
								}
								position++
							case '_':
								if buffer[position] != rune('_') {
									goto l130
								}
								position++
							default:
								if c := buffer[position]; c < rune('a') || c > rune('z') {
									goto l130
								}
								position++
							}
						}

						add(ruleID1, position131)
					}
					goto l129
				l130:
					position, tokenIndex = position130, tokenIndex130
				}
				add(ruleID, position126)
			}
			return true
		l125:
			position, tokenIndex = position125, tokenIndex125
			return false
		},
		/* 27 FIRST_CHAR <- <((&('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z') [A-Z]) | (&('_') '_') | (&('a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z') [a-z]))> */
		nil,
		/* 28 ID1 <- <((&('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9') [0-9]) | (&('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z') [A-Z]) | (&('_') '_') | (&('a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z') [a-z]))> */
		nil,
		/* 29 INTEGER <- <(INT / ('-' INT))> */
		func() bool {
			position135, tokenIndex135 := position, tokenIndex
			{
				position136 := position
				{
					position137, tokenIndex137 := position, tokenIndex
					if !_rules[ruleINT]() {
						goto l138
					}
					goto l137
				l138:
					position, tokenIndex = position137, tokenIndex137
					if buffer[position] != rune('-') {
						goto l135
					}
					position++
					if !_rules[ruleINT]() {
						goto l135
					}
				}
			l137:
				add(ruleINTEGER, position136)
			}
			return true
		l135:
			position, tokenIndex = position135, tokenIndex135
			return false
		},
		/* 30 BOOLEAN <- <(('t' 'r' 'u' 'e') / ('f' 'a' 'l' 's' 'e'))> */
		func() bool {
			position139, tokenIndex139 := position, tokenIndex
			{
				position140 := position
				{
					position141, tokenIndex141 := position, tokenIndex
					if buffer[position] != rune('t') {
						goto l142
					}
					position++
					if buffer[position] != rune('r') {
						goto l142
					}
					position++
					if buffer[position] != rune('u') {
						goto l142
					}
					position++
					if buffer[position] != rune('e') {
						goto l142
					}
					position++
					goto l141
				l142:
					position, tokenIndex = position141, tokenIndex141
					if buffer[position] != rune('f') {
						goto l139
					}
					position++
					if buffer[position] != rune('a') {
						goto l139
					}
					position++
					if buffer[position] != rune('l') {
						goto l139
					}
					position++
					if buffer[position] != rune('s') {
						goto l139
					}
					position++
					if buffer[position] != rune('e') {
						goto l139
					}
					position++
				}
			l141:
				add(ruleBOOLEAN, position140)
			}
			return true
		l139:
			position, tokenIndex = position139, tokenIndex139
			return false
		},
		/* 31 STRING <- <('"' CHARS_IN_STRING* '"')> */
		func() bool {
			position143, tokenIndex143 := position, tokenIndex
			{
				position144 := position
				if buffer[position] != rune('"') {
					goto l143
				}
				position++
			l145:
				{
					position146, tokenIndex146 := position, tokenIndex
					{
						position147 := position
						{
							position148, tokenIndex148 := position, tokenIndex
							if buffer[position] != rune('-') {
								goto l149
							}
							position++
							goto l148
						l149:
							position, tokenIndex = position148, tokenIndex148
							{
								switch buffer[position] {
								case '-':
									if buffer[position] != rune('-') {
										goto l146
									}
									position++
								case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
									if c := buffer[position]; c < rune('A') || c > rune('Z') {
										goto l146
									}
									position++
								case '?':
									if buffer[position] != rune('?') {
										goto l146
									}
									position++
								case ';':
									if buffer[position] != rune(';') {
										goto l146
									}
									position++
								case ':':
									if buffer[position] != rune(':') {
										goto l146
									}
									position++
								case '.':
									if buffer[position] != rune('.') {
										goto l146
									}
									position++
								case ',':
									if buffer[position] != rune(',') {
										goto l146
									}
									position++
								case '+':
									if buffer[position] != rune('+') {
										goto l146
									}
									position++
								case '*':
									if buffer[position] != rune('*') {
										goto l146
									}
									position++
								case ')':
									if buffer[position] != rune(')') {
										goto l146
									}
									position++
								case '(':
									if buffer[position] != rune('(') {
										goto l146
									}
									position++
								case '&':
									if buffer[position] != rune('&') {
										goto l146
									}
									position++
								case '%':
									if buffer[position] != rune('%') {
										goto l146
									}
									position++
								case '$':
									if buffer[position] != rune('$') {
										goto l146
									}
									position++
								case '#':
									if buffer[position] != rune('#') {
										goto l146
									}
									position++
								case '!':
									if buffer[position] != rune('!') {
										goto l146
									}
									position++
								case ' ':
									if buffer[position] != rune(' ') {
										goto l146
									}
									position++
								case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
									if c := buffer[position]; c < rune('0') || c > rune('9') {
										goto l146
									}
									position++
								default:
									if c := buffer[position]; c < rune('a') || c > rune('z') {
										goto l146
									}
									position++
								}
							}

						}
					l148:
						add(ruleCHARS_IN_STRING, position147)
					}
					goto l145
				l146:
					position, tokenIndex = position146, tokenIndex146
				}
				if buffer[position] != rune('"') {
					goto l143
				}
				position++
				add(ruleSTRING, position144)
			}
			return true
		l143:
			position, tokenIndex = position143, tokenIndex143
			return false
		},
		/* 32 CHARS_IN_STRING <- <('-' / ((&('-') '-') | (&('A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z') [A-Z]) | (&('?') '?') | (&(';') ';') | (&(':') ':') | (&('.') '.') | (&(',') ',') | (&('+') '+') | (&('*') '*') | (&(')') ')') | (&('(') '(') | (&('&') '&') | (&('%') '%') | (&('$') '$') | (&('#') '#') | (&('!') '!') | (&(' ') ' ') | (&('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9') [0-9]) | (&('a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z') [a-z])))> */
		nil,
		/* 33 INT <- <[0-9]+> */
		func() bool {
			position152, tokenIndex152 := position, tokenIndex
			{
				position153 := position
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l152
				}
				position++
			l154:
				{
					position155, tokenIndex155 := position, tokenIndex
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l155
					}
					position++
					goto l154
				l155:
					position, tokenIndex = position155, tokenIndex155
				}
				add(ruleINT, position153)
			}
			return true
		l152:
			position, tokenIndex = position152, tokenIndex152
			return false
		},
		/* 34 ARRAY <- <('[' ']' TYPE '[' WHITESPACE_ANY ARRAY_CONTENT WHITESPACE_ANY ']')> */
		func() bool {
			position156, tokenIndex156 := position, tokenIndex
			{
				position157 := position
				if buffer[position] != rune('[') {
					goto l156
				}
				position++
				if buffer[position] != rune(']') {
					goto l156
				}
				position++
				if !_rules[ruleTYPE]() {
					goto l156
				}
				if buffer[position] != rune('[') {
					goto l156
				}
				position++
				if !_rules[ruleWHITESPACE_ANY]() {
					goto l156
				}
				{
					position158 := position
					if !_rules[ruleVALUE]() {
						goto l156
					}
				l159:
					{
						position160, tokenIndex160 := position, tokenIndex
						if !_rules[ruleARRAY_CONTENT1]() {
							goto l160
						}
						goto l159
					l160:
						position, tokenIndex = position160, tokenIndex160
					}
					add(ruleARRAY_CONTENT, position158)
				}
				if !_rules[ruleWHITESPACE_ANY]() {
					goto l156
				}
				if buffer[position] != rune(']') {
					goto l156
				}
				position++
				add(ruleARRAY, position157)
			}
			return true
		l156:
			position, tokenIndex = position156, tokenIndex156
			return false
		},
		/* 35 ARRAY_CONTENT <- <(VALUE ARRAY_CONTENT1*)> */
		nil,
		/* 36 ARRAY_CONTENT1 <- <(WHITESPACE_ANY ',' WHITESPACE_ANY VALUE ARRAY_CONTENT1*)> */
		func() bool {
			position162, tokenIndex162 := position, tokenIndex
			{
				position163 := position
				if !_rules[ruleWHITESPACE_ANY]() {
					goto l162
				}
				if buffer[position] != rune(',') {
					goto l162
				}
				position++
				if !_rules[ruleWHITESPACE_ANY]() {
					goto l162
				}
				if !_rules[ruleVALUE]() {
					goto l162
				}
			l164:
				{
					position165, tokenIndex165 := position, tokenIndex
					if !_rules[ruleARRAY_CONTENT1]() {
						goto l165
					}
					goto l164
				l165:
					position, tokenIndex = position165, tokenIndex165
				}
				add(ruleARRAY_CONTENT1, position163)
			}
			return true
		l162:
			position, tokenIndex = position162, tokenIndex162
			return false
		},
		/* 37 MAP <- <('(' KEY_VALUE_PAIRS ')')> */
		nil,
		/* 38 KEY_VALUE_PAIRS <- <(STRING ':' VALUE KEY_VALUE_PAIRS1*)> */
		func() bool {
			position167, tokenIndex167 := position, tokenIndex
			{
				position168 := position
				if !_rules[ruleSTRING]() {
					goto l167
				}
				if buffer[position] != rune(':') {
					goto l167
				}
				position++
				if !_rules[ruleVALUE]() {
					goto l167
				}
			l169:
				{
					position170, tokenIndex170 := position, tokenIndex
					if !_rules[ruleKEY_VALUE_PAIRS1]() {
						goto l170
					}
					goto l169
				l170:
					position, tokenIndex = position170, tokenIndex170
				}
				add(ruleKEY_VALUE_PAIRS, position168)
			}
			return true
		l167:
			position, tokenIndex = position167, tokenIndex167
			return false
		},
		/* 39 KEY_VALUE_PAIRS1 <- <(',' KEY_VALUE_PAIRS KEY_VALUE_PAIRS1*)> */
		func() bool {
			position171, tokenIndex171 := position, tokenIndex
			{
				position172 := position
				if buffer[position] != rune(',') {
					goto l171
				}
				position++
				if !_rules[ruleKEY_VALUE_PAIRS]() {
					goto l171
				}
			l173:
				{
					position174, tokenIndex174 := position, tokenIndex
					if !_rules[ruleKEY_VALUE_PAIRS1]() {
						goto l174
					}
					goto l173
				l174:
					position, tokenIndex = position174, tokenIndex174
				}
				add(ruleKEY_VALUE_PAIRS1, position172)
			}
			return true
		l171:
			position, tokenIndex = position171, tokenIndex171
			return false
		},
		/* 40 WHITESPACE_AT_LEAST_ONE <- <WHITESPACEC+> */
		func() bool {
			position175, tokenIndex175 := position, tokenIndex
			{
				position176 := position
				if !_rules[ruleWHITESPACEC]() {
					goto l175
				}
			l177:
				{
					position178, tokenIndex178 := position, tokenIndex
					if !_rules[ruleWHITESPACEC]() {
						goto l178
					}
					goto l177
				l178:
					position, tokenIndex = position178, tokenIndex178
				}
				add(ruleWHITESPACE_AT_LEAST_ONE, position176)
			}
			return true
		l175:
			position, tokenIndex = position175, tokenIndex175
			return false
		},
		/* 41 WHITESPACE_ANY <- <WHITESPACEC*> */
		func() bool {
			{
				position180 := position
			l181:
				{
					position182, tokenIndex182 := position, tokenIndex
					if !_rules[ruleWHITESPACEC]() {
						goto l182
					}
					goto l181
				l182:
					position, tokenIndex = position182, tokenIndex182
				}
				add(ruleWHITESPACE_ANY, position180)
			}
			return true
		},
		/* 42 WHITESPACEC <- <((&('\n') '\n') | (&('\t') '\t') | (&(' ') ' '))> */
		func() bool {
			position183, tokenIndex183 := position, tokenIndex
			{
				position184 := position
				{
					switch buffer[position] {
					case '\n':
						if buffer[position] != rune('\n') {
							goto l183
						}
						position++
					case '\t':
						if buffer[position] != rune('\t') {
							goto l183
						}
						position++
					default:
						if buffer[position] != rune(' ') {
							goto l183
						}
						position++
					}
				}

				add(ruleWHITESPACEC, position184)
			}
			return true
		l183:
			position, tokenIndex = position183, tokenIndex183
			return false
		},
		/* 43 AT_LEAST_ONE_SPACE <- <' '+> */
		func() bool {
			position186, tokenIndex186 := position, tokenIndex
			{
				position187 := position
				if buffer[position] != rune(' ') {
					goto l186
				}
				position++
			l188:
				{
					position189, tokenIndex189 := position, tokenIndex
					if buffer[position] != rune(' ') {
						goto l189
					}
					position++
					goto l188
				l189:
					position, tokenIndex = position189, tokenIndex189
				}
				add(ruleAT_LEAST_ONE_SPACE, position187)
			}
			return true
		l186:
			position, tokenIndex = position186, tokenIndex186
			return false
		},
		/* 44 JUST_SPACES <- <' '*> */
		func() bool {
			{
				position191 := position
			l192:
				{
					position193, tokenIndex193 := position, tokenIndex
					if buffer[position] != rune(' ') {
						goto l193
					}
					position++
					goto l192
				l193:
					position, tokenIndex = position193, tokenIndex193
				}
				add(ruleJUST_SPACES, position191)
			}
			return true
		},
	}
	p.rules = _rules
	return nil
}
